function [Avu, Avxux, Avxuy, Avyuy, Aconv, Avucx, Avucy, Avuc2, Avxp, Avyp, Aqxpx, Aqxpy, Aqypy] = calc_stiff(N, vertices, meshes, u1, u2, c, T, P2P2, P2xP2x, P2xP2y, P2yP2y, P2P2xP2, P2P2yP2, P2P2P2x, P2P2P2y, P2P2P2s, P2xP1, P2yP1, P1xP1x, P1xP1y, P1yP1y)
Nv = size(vertices, 1);
Avu = zeros(Nv);
Avxux = zeros(Nv);
Avxuy = zeros(Nv);
Avyuy = zeros(Nv);
Aconv = zeros(Nv);
Avucx = zeros(Nv);
Avucy = zeros(Nv);
Avuc2 = zeros(Nv);
Avxp = zeros(Nv, N);
Avyp = zeros(Nv, N);
Aqxpx = zeros(N);
Aqxpy = zeros(N);
Aqypy = zeros(N);

%Avu = sparse(Nv, Nv);
%Avxux = sparse(Nv, Nv);
%Avxuy = sparse(Nv, Nv);
%Avyuy = sparse(Nv, Nv);
%Aconv = sparse(Nv, Nv);
%Avucx = sparse(Nv, Nv);
%Avucy = sparse(Nv, Nv);
%Avuc2 = sparse(Nv, Nv);
%Avxp = sparse(Nv, N);
%Avyp = sparse(Nv, N);
%Aqxpx = sparse(N, N);
%Aqxpy = sparse(N, N);
%Aqypy = sparse(N, N);
area = zeros(size(meshes, 1), 1);
for i = 1: size(meshes, 1)
    v1 = vertices(meshes(i, 1), :); %1-by-2
    v2 = vertices(meshes(i, 2), :);
    v3 = vertices(meshes(i, 3), :); 
    Jacobi = T(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    assert(Jacobi > 0, int2str(i));
    Avu(meshes(i, :), meshes(i, :)) = Avu(meshes(i, :), meshes(i, :)) + Jacobi*P2P2();
    Avxux(meshes(i, :), meshes(i, :)) = Avxux(meshes(i, :), meshes(i, :)) + Jacobi*P2xP2x(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    Avxuy(meshes(i, :), meshes(i, :)) = Avxuy(meshes(i, :), meshes(i, :)) + Jacobi*P2xP2y(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    Avyuy(meshes(i, :), meshes(i, :)) = Avyuy(meshes(i, :), meshes(i, :)) + Jacobi*P2yP2y(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    Aconv(meshes(i, :), meshes(i, :)) = Aconv(meshes(i, :), meshes(i, :)) + Jacobi*reshape(P2P2xP2(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2))*u1(meshes(i, :)) + P2P2yP2(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2))*u2(meshes(i, :)), [6, 6]);
    Avucx(meshes(i, :), meshes(i, :)) = Avucx(meshes(i, :), meshes(i, :)) + Jacobi*reshape(P2P2P2x(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2))*c(meshes(i, :)), [6, 6]);
    Avucy(meshes(i, :), meshes(i, :)) = Avucy(meshes(i, :), meshes(i, :)) + Jacobi*reshape(P2P2P2y(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2))*c(meshes(i, :)), [6, 6]);
    Avuc2(meshes(i, :), meshes(i, :)) = Avuc2(meshes(i, :), meshes(i, :)) + Jacobi*reshape(P2P2P2s()*reshape(c(meshes(i, :))*c(meshes(i, :))', [36, 1]), [6, 6]);
    Avxp(meshes(i, :), meshes(i, 1: 3)) = Avxp(meshes(i, :), meshes(i, 1: 3)) + Jacobi*P2xP1(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    Avyp(meshes(i, :), meshes(i, 1: 3)) = Avyp(meshes(i, :), meshes(i, 1: 3)) + Jacobi*P2yP1(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    area(i) = Jacobi;
end
area = area + max(area) - min(area);
for i = 1: size(meshes, 1)
    v1 = vertices(meshes(i, 1), :); %1-by-2
    v2 = vertices(meshes(i, 2), :);
    v3 = vertices(meshes(i, 3), :); 
    Jacobi = area(i);
    Aqxpx(meshes(i, 1: 3), meshes(i, 1: 3)) = Aqxpx(meshes(i, 1: 3), meshes(i, 1: 3)) + Jacobi*P1xP1x(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    Aqxpy(meshes(i, 1: 3), meshes(i, 1: 3)) = Aqxpy(meshes(i, 1: 3), meshes(i, 1: 3)) + Jacobi*P1xP1y(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
    Aqypy(meshes(i, 1: 3), meshes(i, 1: 3)) = Aqypy(meshes(i, 1: 3), meshes(i, 1: 3)) + Jacobi*P1yP1y(v1(1), v2(1), v3(1), v1(2), v2(2), v3(2));
end
Avu = sparse(Avu);
Avxux = sparse(Avxux);
Avxuy = sparse(Avxuy);
Avyuy = sparse(Avyuy);
Aconv = sparse(Aconv);
Avucx = sparse(Avucx);
Avucy = sparse(Avucy);
Avuc2 = sparse(Avuc2);
Avxp = sparse(Avxp);
Avyp = sparse(Avyp);
Aqxpx = sparse(Aqxpx);
Aqxpy = sparse(Aqxpy);
Aqypy = sparse(Aqypy);
end