clear;
h = 2^(-5);
Re = 1;
Ca = 1;
rho = 10;
Ae = 25;
nu = 0.45;
Pe = 100;
mu = Ae/2/(1 + nu);
lambda = Ae*nu/(1 - 2*nu)/(1 + nu);
gamma1 = 1.5;
gamma2 = 1;
Lambda1 = 10;
Lambda2 = 0.1;
dt = 0.1;
epsilon = 1/20;
shuttle = 3;
syms x y real;
dis = 0.3 - sqrt((x - 1/2)^2 + (y - 1/2)^2);
c0 = tanh(dis/sqrt(2)/epsilon);
c0 = matlabFunction(c0);
[NS, verticesS, meshesS, GammaS, transS, G2mS, eS] = init_meshes(h, [3, 4, 0, 1, 1, 0, 1/2, 1/2, 0, 0]');
[NL, verticesL, meshesL, GammaL, transL, G2mL, eL] = init_meshes(h, [3, 4, 0, 1, 1, 0, 1/2, 1/2, 1, 1]');
[T, P2P2, P2xP2x, P2xP2y, P2yP2y, P2xP1, P2yP1, P1xP1x, P1xP1y, P1yP1y, P2P2xP2, P2P2yP2, P2P2P2x, P2P2P2y, P2P2P2s, P2P2xP2nG, P2P2yP2nG] = init_feaspace;
n = size(GammaS, 1); %number of triangle on the interface
NvS = size(verticesS, 1);
NvL = size(verticesL, 1);
Nv = NvS + NvL; %number of DoFs of P2
cup = [zeros(2*Nv, 1); c0(verticesL(:, 1), verticesL(:, 2)); zeros(NvL + NL + n, 1)];
idxuS1 = 1: NvS;
idxuS2 = NvS + 1: 2*NvS;
idxuL1 = 2*NvS + 1: 2*NvS + NvL;
idxuL2 = 2*NvS + NvL + 1: 2*Nv;
idxc = 2*Nv + 1: 2*Nv + NvL;
%idxmu = 2*Nv + NvL + 1: 2*(Nv + NvL);
%idxp = 2*(Nv + NvL) + 1: 2*(Nv + NvL) + NL;
%idxlam = 2*(Nv + NvL) + NL + 1: 2*(Nv + NvL) + NL + n;
free_u = prod(verticesS.*(1 - verticesS), 2) ~= 0;
%free_u = [free_u; free_u; ~zeros(4*NvL + NL + n + 1, 1)];
free_u = [free_u; free_u; verticesL(:, 1).*(1 - verticesL(:, 1))~= 0; verticesL(:, 2) ~= 1; ~zeros(2*NvL + NL + n, 1)];
cw = zeros(2*NL, 1);
idxw1 = 1: NL;
idxw2 = NL + 1: 2*NL;
idxwG1 = [GammaL(:, 1); GammaL(:, 2)];
idxwG2 = [GammaL(:, 1); GammaL(:, 2)] + NL;
free_w = [verticesL(1: NL, 1).*(1 - verticesL(1: NL, 1)) ~= 0; verticesL(1: NL, 2) ~= 1];
free_w([idxwG1; idxwG2]) = false;
[AvuS, AvxuxS, AvxuyS, AvyuyS] = init_stiff(verticesS, meshesS, T, P2P2, P2xP2x, P2xP2y, P2yP2y);
uS1 = zeros(NvS, 1);
uS2 = zeros(NvS, 1);
for k = 1: 1/dt
    [AvuL, AvxuxL, AvxuyL, AvyuyL, AconvL, AvucxL, AvucyL, Avuc2L, AvxpL, AvypL, AqxpxL, AqxpyL, AqypyL] = calc_stiff(NL, verticesL, meshesL, cup(idxuL1) - transL*cw(idxw1), cup(idxuL2) - transL*cw(idxw2), cup(idxc), T, P2P2, P2xP2x, P2xP2y, P2yP2y, P2P2xP2, P2P2yP2, P2P2P2x, P2P2P2y, P2P2P2s, P2xP1, P2yP1, P1xP1x, P1xP1y, P1yP1y);
    gamma = (gamma1 + gamma2 + (gamma1 - gamma2)*sin(pi*cup(idxc(GammaL))/2))/2;
    [AvSuS, AvLuL, AvSuL, AvsusG, AvuxcnG, AvuycnG, Avn1S, Avn2S, Avn1L, Avn2L, bS1, bS2] = calc_upper(shuttle, epsilon, verticesS, meshesS, GammaS, G2mS, verticesL, meshesL, GammaL, G2mL, cup(idxc), gamma, P2P2xP2nG, P2P2yP2nG);
    ASS1 = rho/dt*[AvuS, sparse(NvS, NvS); sparse(NvS, NvS), AvuS];
    ASS2 = [(2*mu + lambda)*AvxuxS + mu*AvyuyS, mu*AvxuyS' + lambda*AvxuyS; mu*AvxuyS + lambda*AvxuyS', mu*AvxuxS + (2*mu + lambda)*AvyuyS];
    ASS3 = [AvsusG, sparse(NvS, NvS); sparse(NvS, NvS), AvsusG]/Re/Ca;
    ASS4 = [AvSuS, sparse(NvS, NvS); sparse(NvS, NvS), AvSuS]/Re/Lambda2;
    ASL = -[AvSuL, sparse(NvS, NvL); sparse(NvS, NvL), AvSuL]/Re/Lambda2;
    ASC = -epsilon/Re/Ca*[AvuxcnG, sparse(NvS, NvL); AvuycnG, sparse(NvS, NvL)];
    ASP = [sparse(NvS, NL), Avn1S; sparse(NvS, NL), Avn2S];
    ALL = [AvuL/dt + AconvL + (2*AvxuxL + AvyuyL)/Re + AvLuL/Re/Lambda2, AvxuyL'/Re; AvxuyL/Re, AvuL/dt + AconvL + (AvxuxL + 2*AvyuyL)/Re + AvLuL/Re/Lambda2];
    ALC = -[sparse(NvL, NvL), AvucxL; sparse(NvL, NvL), AvucyL]/Re/Ca;
    ALP = [AvxpL, -Avn1L; AvypL, -Avn2L];
    ACC = [epsilon*(AvxuxL + AvyuyL) + (3*Avuc2L - AvuL)/epsilon + AvLuL/dt/Lambda1, -AvuL; AvuL/dt + AconvL, (AvxuxL + AvyuyL)/Pe];
    A = [ASS1 + dt*(ASS2 + ASS3) + ASS4, ASL, ASC, ASP; ASL', ALL, ALC, ALP; sparse(2*NvL, 2*Nv), ACC, sparse(2*NvL, NL + n); ASP', ALP', sparse(NL + n, 2*NvL + NL + n)];
    dgamma = pi/4*(gamma1 - gamma2)*cos(pi*cup(idxc)/2);
    b = [ASS1*cup([idxuS1, idxuS2]) - ASS2*[uS1; uS2] - ASS3*([uS1 + verticesS(:, 1); uS2 + verticesS(:, 2)]) + [bS1; bS2]; AvuL*cup(idxuL1)/dt; AvuL*cup(idxuL2)/dt; (2/epsilon*Avuc2L + AvLuL/Lambda1/dt)*cup(idxc) - AvLuL*dgamma; AvuL*cup(idxc)/dt; zeros(NL + n, 1)];
    cup(free_u) = A(free_u, free_u) \ b(free_u);
    uS1 = uS1 + dt*cup(idxuS1);
    uS2 = uS2 + dt*cup(idxuS2);

    A = sparse([3*AqxpxL + AqypyL, AqxpyL' + AqxpyL; AqxpyL + AqxpyL', AqxpxL + 3*AqypyL]);
    cw(:) = 0;
    cw(idxwG1) = cup(idxuS1([GammaS(:, 1); GammaS(:, 2)]));
    cw(idxwG2) = cup(idxuS2([GammaS(:, 1); GammaS(:, 2)]));
    b = -A*cw;
    cw(free_w) = A(free_w, free_w) \ b(free_w);
    verticesL = verticesL + dt*transL*[cw(idxw1), cw(idxw2)];
%    figure;
 %   pdemesh(verticesL', eL, meshesL(:, [1: 3, 6, 4, 5])', 'NodeLabels', 'on', 'ElementLabels', 'on');
%    trisurf([meshesS(:, [1, 6, 5]); meshesS(:, [2, 4, 6]); meshesS(:, [3, 5, 4]); meshesS(:, [4, 5, 6])], verticesS(:, 1), verticesS(:, 2), uS2);
%    trisurf([meshesL(:, [1, 6, 5]); meshesL(:, [2, 4, 6]); meshesL(:, [3, 5, 4]); meshesL(:, [4, 5, 6])], verticesL(:, 1), verticesL(:, 2), cup(idxc));
end
